main: com.runetooncraft.plugins.EasyMobArmory.EMA
name: EasyMobArmory
version: 1.1.0
depend: [BKCommonLib]
author: Deery50
description: Easily set mob items.
commands:
    EasyMobArmory:
        description: Base command for EasyMobArmory
        usage: |
    ema:
        description: Base command for EasyMobArmory
        usage: |
permissions:
    ema.use:
        description: Gives access to add armor to Mobs.
    ema.spawners:
        description: Gives access to create and change EMA spawners.
    ema.eggs:
        description: Allows player to right click with EMA eggs to spawn duplicate entities.