main: com.runetooncraft.plugins.EasyMobArmory.EMA
name: EasyMobArmory
version: 1.0.0
author: Deery50
description: Easily set mob items.
commands:
    EasyMobArmory:
        description: Base command for EasyMobArmory
        usage: |
    ema:
        description: Base command for EasyMobArmory
        usage: |
permissions:
    ema.use:
        description: Gives access to add armor to Mobs